# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3fb056b9250967b11801486012ac75e61f52e6cce04c3efb0f42f5d7849dbf6cd95a800e7e3f09734b506ef52a90a39181386567b9455292540f323faf4d70

test:
  secret_key_base: 68ffe53c1a5b457f0cbfcf4a20a5658851995196d493342350a07a51b243090410b42294a48a2b0fb51ea9bddb8babc62f229013d0b28e4d35a5d7c78042cb72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
